import * as yup from 'yup';

export const newTransactionSchema = yup.object({
  amounts: yup
    .array()
    .required()
    .of(
      yup.object({
        account: yup.string().required(),
        amount: yup.number().required(),
        category: yup.string().required(),
        id: yup.string().uuid().required(), // ID is generated by the client
        isCredit: yup.boolean().required(),
        notes: yup.string(),
      })
    ),
  date: yup.date().required(), // TODO Better client error message for this field
  description: yup.string().required(),
  id: yup.string().uuid().required(), // ID is generated by the client
  type: yup.string().required(),
});
